### ISSUE TITLE
build fails against latest wayfire master branch

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#10]
hello, wayfire updated to wlroots version 0.17.4 recently.  maybe that is the cause? 

ninja: Entering directory `build'
[14/40] Compiling C object toplevel-grabber/tl_grabber_test.p/toplevel-grabber-test.c.o
../toplevel-grabber/toplevel-grabber-test.c: In function ‘tl_cb’:
../toplevel-grabber/toplevel-grabber-test.c:29:25: warning: unused parameter ‘data’ [-Wunused-parameter]
   29 | static void tl_cb(void* data, struct tl_grabber* gr) {
      |                   ~~~~~~^~~~
[20/40] Compiling C object src/libcellib.a.p/cellrenderertextish.c.o
FAILED: src/libcellib.a.p/cellrenderertextish.c.o 
cc -Isrc/libcellib.a.p -Isrc -I../src -Iinput-inhibitor -I../input-inhibitor -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/gio-unix-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -pthread -w -MD -MQ src/libcellib.a.p/cellrenderertextish.c.o -MF src/libcellib.a.p/cellrenderertextish.c.o.d -o src/libcellib.a.p/cellrenderertextish.c.o -c ../src/cellrenderertextish.c
../src/cellrenderertextish.c: In function ‘cell_renderer_textish_class_init’:
../src/cellrenderertextish.c:821:57: error: assignment to ‘GtkCellEditable * (*)(GtkCellRenderer *, GdkEvent *, GtkWidget *, const gchar *, const GdkRectangle *, const GdkRectangle *, GtkCellRendererState)’ {aka ‘struct _GtkCellEditable * (*)(struct _GtkCellRenderer *, union _GdkEvent *, struct _GtkWidget *, const char *, const struct _cairo_rectangle_int *, const struct _cairo_rectangle_int *, GtkCellRendererState)’} from incompatible pointer type ‘GtkCellEditable * (*)(GtkCellRenderer *, GdkEvent *, GtkWidget *, const gchar *, GdkRectangle *, GdkRectangle *, GtkCellRendererState)’ {aka ‘struct _GtkCellEditable * (*)(struct _GtkCellRenderer *, union _GdkEvent *, struct _GtkWidget *, const char *, struct _cairo_rectangle_int *, struct _cairo_rectangle_int *, GtkCellRendererState)’} [-Wincompatible-pointer-types]
  821 |         ((GtkCellRendererClass *) klass)->start_editing = (GtkCellEditable* (*) (GtkCellRenderer*, GdkEvent*, GtkWidget*, const gchar*, GdkRectangle*, GdkRectangle*, GtkCellRendererState)) cell_renderer_textish_real_start_editing;
      |                                                         ^
../src/cellrenderertextish.c:822:50: error: assignment to ‘void (*)(GtkCellRenderer *, cairo_t *, GtkWidget *, const GdkRectangle *, const GdkRectangle *, GtkCellRendererState)’ {aka ‘void (*)(struct _GtkCellRenderer *, struct _cairo *, struct _GtkWidget *, const struct _cairo_rectangle_int *, const struct _cairo_rectangle_int *, GtkCellRendererState)’} from incompatible pointer type ‘void (*)(GtkCellRenderer *, cairo_t *, GtkWidget *, GdkRectangle *, GdkRectangle *, GtkCellRendererState)’ {aka ‘void (*)(struct _GtkCellRenderer *, struct _cairo *, struct _GtkWidget *, struct _cairo_rectangle_int *, struct _cairo_rectangle_int *, GtkCellRendererState)’} [-Wincompatible-pointer-types]
  822 |         ((GtkCellRendererClass *) klass)->render = (void (*) (GtkCellRenderer*, cairo_t*, GtkWidget*, GdkRectangle*, GdkRectangle*, GtkCellRendererState)) cell_renderer_textish_real_render;
      |                                                  ^
../src/cellrenderertextish.c:823:52: error: assignment to ‘void (*)(GtkCellRenderer *, GtkWidget *, const GdkRectangle *, gint *, gint *, gint *, gint *)’ {aka ‘void (*)(struct _GtkCellRenderer *, struct _GtkWidget *, const struct _cairo_rectangle_int *, int *, int *, int *, int *)’} from incompatible pointer type ‘void (*)(GtkCellRenderer *, GtkWidget *, GdkRectangle *, gint *, gint *, gint *, gint *)’ {aka ‘void (*)(struct _GtkCellRenderer *, struct _GtkWidget *, struct _cairo_rectangle_int *, int *, int *, int *, int *)’} [-Wincompatible-pointer-types]
  823 |         ((GtkCellRendererClass *) klass)->get_size = (void (*) (GtkCellRenderer*, GtkWidget*, GdkRectangle*, gint*, gint*, gint*, gint*)) cell_renderer_textish_real_get_size;
      |                                                    ^
[29/40] Compiling C++ object src/wstroke-config.p/actiondb.cc.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().

**Comment by dkondor** [comment]
Hi,
thanks for reporting -- I think this is very likely caused by not an update to wlroots / Wayfire, but to your C compiler which now rejects code that is auto-generated by Vala. If you have the Vala compiler (`valac`) installed, could you try compiling this branch:
https://github.com/dkondor/wstroke/tree/rebuild_vala ? (it regenerates the file in question and applies the correct flags)
If it doesn't work, I'll try to figure out which compiler flags to add here.

**Comment by mrsteve0924** [comment]
yes that worked. i installed vala and reran meson and built successfully.  thanks

**Comment by dkondor** [comment]
Thanks for testing, I'll swap the two branches then!

**Comment by dkondor** [comment]
Main branch should build now, requiring `valac`; additionally, the `no_vala` branch also should build (added exceptions to the errors generated).

**Comment by mrsteve0924** [comment]
sweet.  i maintain the aur package so i guess i'll need to add the vala package as a make dependency
