### ISSUE TITLE
Wayfire 0.9/wlroots 0.18 compatibility

### ISSUE THREAD

**Issue by wooque** [dkondor/wstroke#12]
Will this package be updated to support latest Wayfire 0.9? 
Currently this package is blocking wlroots 0.18/Wayfire 0.9 to migrate from Debian unstable to Debian testing.

**Comment by dkondor** [comment]
Hi,
actually, it already supports Wayfire 0.9 (I upgraded a couple of weeks ago). But I'm still using wlroots 0.17.2, so I'm not sure if version 0.18 would work as well. Note that I limited the dependency version in the Debian package out of caution, since I was expecting breaking changes. So I think that the dependency could be updated without issues; should I upload a new package to mentors?

**Comment by wooque** [comment]
@dkondor I'm not a Debian developer, so I'm not familiar with the process of pushing updates. I'm just a casual observer of tracking.debian.org that noticed that wlroots is blocked because of wayfire and wayfire is blocked because of wstroke, and soon to be released sway 1.10 will be blocked because of wlroots, which I hope to get hands on in testing :)

**Comment by dkondor** [comment]
I've been able to update the package in unstable:
https://packages.debian.org/sid/wstroke
I hope this fixes the issue (note: both Wayfire and wstroke still depends on wlroots 0.17 though, so that might present additional issues -- updating wstroke would be simple, but it depends on Wayfire)

**Comment by wooque** [comment]
@dkondor wayfire 0.9 in unstable is built against wlroots 0.18 already, because wlroots 0.18 is in unstable for a while. Relevant commit in wayfire (https://salsa.debian.org/debian/wayfire/-/commit/43ec3cff73512d7794863b853d80ca970271c946)

**Comment by dkondor** [comment]
That's looks strange, as the binary in unstable still depends on `libwlroots12t64` (which is version 0.17.4):
https://packages.debian.org/sid/wayfire
Nevertheless now both seem OK to migrate to testing, but needs to wait 5 days after the update to wstroke:
https://tracker.debian.org/pkg/wstroke
https://tracker.debian.org/pkg/wayfire
I'll keep an eye on this to see if any more issues come up.

**Comment by wooque** [comment]
Thanks. 
Seems that wlroots 0.17 -> 0.18 transition is problematic regardless of wayfire, as there are still packages that depend on older 0.17.
There is now this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085192.
