### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#2]
getting an error on ninja -C build.  this is the first error of several.

![ninja -C build](https://github.com/dkondor/wstroke/assets/37476191/37f0d5ef-2f49-45b5-8a69-f04134c87c4e)

got a couple of NO;s on meson build.  not sure if important
![meson build](https://github.com/dkondor/wstroke/assets/37476191/a8342ef9-991d-497c-b880-9398f19959cb)

would be great to get this to build.  i do miss easystroke not working on wayland

**Comment by dkondor** [comment]
Hi,
it seems there are a lot of changes in the latest wlroots + Wayfire that I haven't been following well.
I started looking into this and made some progress adapting code. You can try out the changes in the [wayfire-0.8](https://github.com/dkondor/wstroke/tree/wayfire-0.8) branch.
I can build it now (using wlroots and Wayfire git), but some functionality is still missing, specifically when actions rely on other Wayfire plugins (e.g. activating Expo or Scale). Also, there could be bugs, especially with multiple outputs (which I cannot test currently). I will try to fix these issues soon. Any feedback is very welcome if you are able to test!

**Comment by mrsteve0924** [comment]
thanks @dkondor. yes a lot of wayfire plugins seem to broken due to recent API changes. 

i'll try to test.

**Comment by mrsteve0924** [comment]
tried building with wayfire-0.8 branch and looks like  same error.  I am using wayfire-git. 

![2023-06-17_16:56:20](https://github.com/dkondor/wstroke/assets/37476191/c2974929-7bb7-4673-b9d0-3377f480cb44)

**Comment by dkondor** [comment]
It's actually a different error :)
I've removed that specific include, but the main issue is the version of wlroots -- I'm on version 0.16.2, based on the latest git. Could you try again and report your Wayfire and wlroots versions if not working? Thanks!

**Comment by mrsteve0924** [comment]
I last updated wayfire git version on june 7 and saw a few commits since then so I rebuilt it.  wlroots  was built as a submodule and should be version 0.16.2.   after that wstroke 0.8 built without issue.

plugin works well.  i do get one annoying bug that the mouse gestures only work on 1 of my 2 displays.  but otherwise really good work.  thanks

**Comment by dkondor** [comment]
Thank you for testing, sounds good! I'll make a few additional tests and then update the main branch
