### ISSUE TITLE
new updates to wayfire break wstroke

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#3]
can't build wstroke against latest wayfire master branch

<details>

<summary>error details</summary>

ninja: Entering directory `build'
[12/37] Compiling C object toplevel-grabber/tl_grabber_test.p/toplevel-grabber-test.c.o
../toplevel-grabber/toplevel-grabber-test.c: In function ‘tl_cb’:
../toplevel-grabber/toplevel-grabber-test.c:29:25: warning: unused parameter ‘data’ [-Wunused-parameter]
   29 | static void tl_cb(void* data, struct tl_grabber* gr) {
      |                   ~~~~~~^~~~
[29/37] Compiling C++ object libwstroke.so.p/easystroke_gestures.cpp.o
FAILED: libwstroke.so.p/easystroke_gestures.cpp.o 
c++ -Ilibwstroke.so.p -I. -I.. -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -I/usr/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O0 -g -fPIC -pthread -DBOOST_ALL_NO_LIB -Wno-unused-parameter -Wno-format-security -DWAYFIRE_PLUGIN -DWLR_USE_UNSTABLE -MD -MQ libwstroke.so.p/easystroke_gestures.cpp.o -MF libwstroke.so.p/easystroke_gestures.cpp.o.d -o libwstroke.so.p/easystroke_gestures.cpp.o -c ../easystroke_gestures.cpp
../easystroke_gestures.cpp: In member function ‘virtual void wstroke::visit(const View*)’:
../easystroke_gestures.cpp:309:54: error: ‘class wf::view_interface_t’ has no member named ‘minimize_request’
  309 |                                         target_view->minimize_request(true);
      |                                                      ^~~~~~~~~~~~~~~~
../easystroke_gestures.cpp:313:57: error: ‘class wf::view_interface_t’ has no member named ‘tiled_edges’
  313 |                                         if(target_view->tiled_edges == wf::TILED_EDGES_ALL)
      |                                                         ^~~~~~~~~~~
../easystroke_gestures.cpp:313:76: error: ‘TILED_EDGES_ALL’ is not a member of ‘wf’
  313 |                                         if(target_view->tiled_edges == wf::TILED_EDGES_ALL)
      |                                                                            ^~~~~~~~~~~~~~~
../easystroke_gestures.cpp:314:62: error: ‘class wf::view_interface_t’ has no member named ‘tile_request’
  314 |                                                 target_view->tile_request(0);
      |                                                              ^~~~~~~~~~~~
../easystroke_gestures.cpp:315:59: error: ‘class wf::view_interface_t’ has no member named ‘tile_request’
  315 |                                         else target_view->tile_request(wf::TILED_EDGES_ALL);
      |                                                           ^~~~~~~~~~~~
../easystroke_gestures.cpp:315:76: error: ‘TILED_EDGES_ALL’ is not a member of ‘wf’
  315 |                                         else target_view->tile_request(wf::TILED_EDGES_ALL);
      |                                                                            ^~~~~~~~~~~~~~~
../easystroke_gestures.cpp:318:54: error: ‘class wf::view_interface_t’ has no member named ‘move_request’
  318 |                                         target_view->move_request();
      |                                                      ^~~~~~~~~~~~
../easystroke_gestures.cpp:326:54: error: ‘class wf::view_interface_t’ has no member named ‘resize_request’
  326 |                                         target_view->resize_request(WLR_EDGE_BOTTOM | WLR_EDGE_RIGHT);
      |                                                      ^~~~~~~~~~~~~~
[35/37] Compiling C++ object wstroke-config.p/actiondb.cc.o
ninja: build stopped: subcommand failed.

</details>

**Comment by dkondor** [comment]
Hi,
thank you for reporting! Seems that there was a refactor in how some window management functions work in Wayfire. I'll have a look and come up with an updated version.

**Comment by dkondor** [comment]
Hi, I've looked into supporting the latest Wayfire with the latest changes. I've created PR #4 with these -- let me know if you have any issues, otherwise I'll merge it in a few days (note: this adds a new dependency to the JSON library also used by Wayfire internally).

**Comment by mrsteve0924** [comment]
Hi thanks for this.  i rebuilt using branch update-wf-api. build failed until i installed nlohmann-json and then built successfully.  rebooted but gestures do not work.

EDIT: i just remembered that I had installed another gesture program in the meantime.   I uninstalled that and now wstroke works.

**Comment by dkondor** [comment]
Great, I'll merge the PR then -- thanks for testing!
