### ISSUE TITLE
mouse gestures not drawn on second monitor 

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#5]
This has been happening since June.  I thought I reported it but I guess not. 

If I try to draw a gesture on my second monitor it just displays a straight line across the monitor.  

![PXL_20231003_023302633](https://github.com/dkondor/wstroke/assets/37476191/a283e87e-9fe1-424c-807d-25b2ead4bada)

**Comment by dkondor** [comment]
Thank you for reporting this! I rarely use multiple monitors, so I did not realize this issue so far. I'll look into this in the coming days.

**Comment by dkondor** [comment]
Actually, this turns out to be easier than expected. I've pushed a fix in the [fix-multi-output](https://github.com/dkondor/wstroke/tree/fix-multi-output) branch. Let me know if you can test and if you see any issues. Thanks!

**Comment by mrsteve0924** [comment]
hey thanks for the quick fix.   i checked out fix-multi-output branch but getting a build error

EDIT:  updated wayfire and now this branch built without error. 
so far gestures working on second monitor

**Comment by dkondor** [comment]
Great to hear! I'll merge the fix to the main branch and close this issue unless you run into more problems
