### ISSUE TITLE
can't record stroke with the button assigned to gestures

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#6]
i've been using wstroke for about 4 months. using imported gestures from easystroke.  today is the first time i actually had to record a stroke with wstroke-config.  I cant get it to accept any gesture i draw.  

any help troubleshooting?

in on wayfire commit 0de95a42. wstroke commit 481e2d2

**Comment by dkondor** [comment]
Hi, thank you for reporting. Which mouse button do you use? Currently, you have to use a different button than the one you normally use, so it is not interpreted by the plugin (or, alternatively, add `wstroke-config` to the list of exceptions). Let me know if this is the issue.

**Comment by mrsteve0924** [comment]
that was it.  needed to use another mouse button.  simple enough. thanks for the help.

**Comment by dkondor** [comment]
That's good. I see now that the dialog text is inconsistent; I think I planned a solution that allows the use of the same button, but apparently never implemented it.

**Comment by dkondor** [comment]
I've remembered the solution for this, so now using the same button should also work.

**Comment by mrsteve0924** [comment]
nice.  i'll check it out. thanks!

EDIT:  yep.  works as expected
