### ISSUE TITLE
cursor moving with open window after gesture

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#7]
Hello, i'm not sure if the issue comes from the wstroke plugin or the follow-focus plugin. 

I have  dual monitors. if i draw a gesture on output 2 which opens a GUI program on output 1, then the  mouse will move to output 1. 

if i draw a gesture on output 2 and the program's GUI windows also opens on output 2  then the cursor will stay on output 2. 

it's not really a terribly big deal. just takes some getting used to. takes me a second to figure out where my cursor is.
i've tried changing some settings in wcm for follow-focus and wstroke but couldn't change the behavior

EDIT: well it's not wstroke.  i opened a web link from thunderbird and the cursor moved to my second monitor where firefox opened.

**Comment by dkondor** [comment]
Yes, I think this is related to the core issue of focusing a newly created view and its output. Another useful test can be to compare wstroke with the "Command" plugin of Wayfire -- the two should have the same behavior.

However, I see that focus handling in wstroke can actually be inconsistent in some edge cases, but in an opposite sense (not focusing the newly created view); I'll add a fix for this, but I don't expect to change the general behavior.

**Comment by mrsteve0924** [comment]
thanks for reviewing.  i created an issue on wayfire's github page.
