### ISSUE TITLE
wlroots ver 17

### ISSUE THREAD

**Issue by mrsteve0924** [dkondor/wstroke#8]
hello, i am trying to re-rebuild this against wlroots 17 which was updated recently.  doesnt want to build.  i've been having issues with wayfire outside of wlroots so not sure if this is my issue or because of the new wlroots version

here is a partial build  output...

![2023-11-27_15:30:36](https://github.com/dkondor/wstroke/assets/37476191/4916d351-32c4-425e-aed0-1a8995128a5a)

**Comment by dkondor** [comment]
Hi,
currently, WStroke only supports the combination of Wayfire 0.8 + wlroots 0.16 (the latest stable version). I see that Wayfire 0.9 now supports wlroots 0.17, so I'll look into this.

**Comment by dkondor** [comment]
Actually, no change was required, just fixing that headers are included properly. I've updated the master branch and it should build with the latest Wayfire and wlroots 0.17 versions. Everything seems to be working, but I did not test extensively -- report here if you see any issues.

**Comment by mrsteve0924** [comment]
good news.  thanks for taking a look.  i'll update to the master branch and test it out. 

EDIT:  working as expected.  thanks again
